---
# disconnected-sync-operator-index tasks

- name: Create pruned redhat-operator-index image with {{ operators_to_sync }}
  shell: |
    opm index prune -f {{ operator_index_container_image }} -p {{ operators_to_sync }} -t {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/olm-mirror/{{ operator_index_name }}:{{ operator_index_tag }}

- name: Push pruned redhat-operator-index image to disconnected registry
  shell: |
    podman push {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/olm-mirror/{{ operator_index_name }}:{{ operator_index_tag }}

- name: Mirror redhat-operator-index images
  shell: |
    oc adm catalog mirror {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/olm-mirror/{{ operator_index_name }}:{{ operator_index_tag }} {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/olm-mirror -a {{ registry_path }}/pull-secret-disconnected.txt --to-manifests={{ bastion_cluster_config_dir }}/olm-mirror-{{ operator_index_tag }}
