---
# sno-post-cluster-install tasks

- name: Create directory for sno cluster configuration items
  file:
    path: "{{ bastion_cluster_config_dir }}"
    state: directory

- name: Create directory per sno cluster
  file:
    path: "{{ bastion_cluster_config_dir }}/{{ item }}"
    state: directory
  with_items: "{{ ai_cluster_ids }}"

- name: Get credentials (kubeconfig) from installed cluster(s)
  get_url:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v1/clusters/{{ ai_cluster_ids[item].cluster_id }}/downloads/files?file_name=kubeconfig"
    dest: "{{ bastion_cluster_config_dir }}/{{ item }}/kubeconfig"
  with_items: "{{ ai_cluster_ids }}"

- name: Get credentials (kubeadmin-password) from installed cluster(s)
  get_url:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v1/clusters/{{ ai_cluster_ids[item].cluster_id }}/downloads/files?file_name=kubeadmin-password"
    dest: "{{ bastion_cluster_config_dir }}/{{ item }}/kubeadmin-password"
  with_items: "{{ ai_cluster_ids }}"

- name: Apply a label to the worker node(s)
  shell: |
    KUBECONFIG={{ bastion_cluster_config_dir }}/{{ item }}/kubeconfig oc label no --all --overwrite jetlag=true
  with_items: "{{ ai_cluster_ids }}"

- name: Add kube-burner sa
  shell: |
    KUBECONFIG={{ bastion_cluster_config_dir }}/{{ item }}/kubeconfig oc create sa kubeburner
  with_items: "{{ ai_cluster_ids }}"
  when: setup_kube_burner_sa | default(true) | bool

- name: Add cluster-admin role to kube-burner sa
  shell: |
    KUBECONFIG={{ bastion_cluster_config_dir }}/{{ item }}/kubeconfig oc adm policy add-cluster-role-to-user -z kubeburner cluster-admin
  with_items: "{{ ai_cluster_ids }}"
  when: setup_kube_burner_sa | default(true) | bool
