---
# ibmcloud-sno-create-ai-cluster default vars

# This will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
assisted_installer_port: 8090

# Manifest for KubeletConfig to adjust max pods
kubelet_config: false

# Manifest for MachineConfig to enable kdump on master nodes
kdump_master_config: false
