---
# install-cluster tasks

- name: Get bastion registry certificate
  slurp:
    src: "{{ registry_path }}/certs/domain.crt"
  register: mirror_cert
  when: use_bastion_registry | default(false)

# The extra "| to_json(ensure_ascii=False) | string" adds an additional "layer"
# of escaping.  I am unsure of why I actually need this additional layer other
# than the api expects a string (and not actual json)
- name: Apply install-config overrides
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ ai_cluster_id }}/install-config"
    method: PATCH
    body_format: json
    status_code: [201]
    return_content: true
    body: "{{ lookup('template', 'install-config-overrides.yml.j2') | from_yaml | to_json(ensure_ascii=False) | string | to_json(ensure_ascii=False) | string }}"
  register: get_install_config

- name: Enable CNV and LSO install
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ ai_cluster_id }}"
    method: PATCH
    body_format: json
    status_code: [201]
    return_content: true
    body:
      olm_operators:
      - name: "cnv"
  when: enable_cnv_install | default(false)

- name: Install cluster
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ ai_cluster_id }}/actions/install"
    method: POST
    status_code: [202]
    return_content: true
    body_format: json
    body: { }

- name: Set initial loop variables
  set_fact:
    boot_order_fixed_hosts: []

- name: Check if cluster installed tasks loop
  include_tasks: check-cluster-install.yml
