---
# Separate tasks to populate static network configuration

- name: Assemble controlplane static network config
  set_fact:
    item_network_config:
      network_yaml: "{{ lookup('template', 'nmstate.yml.j2') }}"
      mac_interface_map: "{{ lookup('template', 'mac_interface_map.json.j2')  }}"

- name: Add {{ item }} ip config
  set_fact:
    static_network_config: "{{ static_network_config + [ item_network_config ] }}"
