---
# ibmcloud-create-ai-cluster default vars

# This will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
assisted_installer_port: 8090

# Manifest to enable or disable mirroring of image registry for acm-d
rhacm_add_acm_d_icsp_manifest: false

# Manifest for KubeletConfig to adjust max pods
kubelet_config: false
