- name: Cleaning up prometheus server
  block:
    - name: Check if prometheus quadlet configured
      ansible.builtin.command: systemctl is-enabled prometheus.service
      ignore_errors: true
      register: prometheus_quadlet_status

    - name: Check if prometheus quadlet is running
      when: prometheus_quadlet_status.stdout != 'not-found'
      ansible.builtin.command: systemctl is-active prometheus.service
      ignore_errors: true
      register: prometheus_quadlet_active_status

    - name: Stop prometheus quadlet
      when: prometheus_quadlet_active_status.stdout == 'active'
      ansible.builtin.systemd:
        name: prometheus.service
        state: stopped

    - name: Disable prometheus quadlet
      when: prometheus_quadlet_status.stdout == 'enabled'
      ansible.builtin.systemd:
        name: prometheus.service
        enabled: false

    - name: Remove prometheus quadlet
      when: prometheus_quadlet_status.stdout != 'not-found'
      ansible.builtin.file:
        path: "{{ hv_metrics_quadlet_dir }}/prometheus.container"
        state: absent

- name: Cleaning up prometheus client
  block:
    - name: Check if nodexporter quadlet configured
      ansible.builtin.command: systemctl is-enabled nodexporter.service
      ignore_errors: true
      register: nodexporter_quadlet_status

    - name: Check if nodexporter quadlet is running
      when: not nodexporter_quadlet_status.stdout == 'not-found'
      ansible.builtin.command: systemctl is-active nodexporter.service
      ignore_errors: true
      register: nodexporter_quadlet_active_status

    - name: Stop nodexporter quadlet
      when: nodexporter_quadlet_active_status.stdout == 'active'
      ansible.builtin.systemd:
        name: nodexporter.service
        state: stopped

    - name: Disable nodexporter quadlet
      when: nodexporter_quadlet_status.stdout == 'enabled'
      ansible.builtin.systemd:
        name: nodexporter.service
        enabled: false

    - name: Remove nodexporter quadlet
      when: not nodexporter_quadlet_status.stdout == 'not-found'
      ansible.builtin.file:
        path: "{{ hv_metrics_quadlet_dir }}/nodexporter.container"
        state: absent

- name: Cleanup working directory
  when: not hv_metrics_cleanup_keep_work_dir | bool
  ansible.builtin.file:
    path: "{{ hv_metrics_work_dir }}"
    state: absent

- name: Remove container images
  block:
    - name: Remove prometheus container image
      ansible.builtin.command: podman rmi {{ hv_metrics_prometheus_container_name }}
      ignore_errors: true

    - name: Remove nodexporter container image
      ansible.builtin.command: podman rmi {{ hv_metrics_node_exporter_container_name }}
      ignore_errors: true

- name: Reconfigure firewalld
  block:
    - name: Check if firewalld is running
      ansible.builtin.command: systemctl is-active firewalld
      ignore_errors: true
      register: hv_metrics_cleanup_firewalld_running

    - name: Remove firewalld rules
      when: hv_metrics_cleanup_firewalld_running.stdout == 'active'
      ansible.builtin.firewalld:
        port: "{{ hv_metrics_server_port }}"
        permanent: true
        immediate: true
        state: disabled

    - name: Remove firewalld rules
      when: hv_metrics_cleanup_firewalld_running.stdout == 'active'
      ansible.builtin.firewalld:
        port: "{{ hv_metrics_client_port }}"
        permanent: true
        immediate: true
        state: disabled