- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Create work directory
  ansible.builtin.file:
    path: "{{ hv_metrics_work_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create prometheus data directory
  ansible.builtin.file:
    path: "{{ hv_metrics_server_podman_data_dir }}"
    state: directory
    mode: "0777"
    owner: root
    group: root

- name: Render prometheus configuration
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: "{{ hv_metrics_server_podman_config_source }}"
    mode: "0644"
    owner: root
    group: root

- name: Put prometheus quadlet configuration
  ansible.builtin.template:
    src: prometheus.container.j2
    dest: "{{ hv_metrics_quadlet_dir }}/prometheus.container"
    mode: "0644"
    owner: root
    group: root

- name: Configure firewall
  block:
    - name: Check if firewalld is running
      ansible.builtin.command: systemctl is-active firewalld
      ignore_errors: true
      register: hv_metrics_server_firewalld_running

    - name: Add firewalld rules
      when: hv_metrics_server_firewalld_running.stdout == 'active'
      ansible.builtin.firewalld:
        port: "{{ hv_metrics_server_port }}"
        zone: public
        permanent: true
        immediate: true
        state: enabled
        protocol: tcp

- name: Start and enable prometheus quadlet
  ansible.builtin.systemd:
    name: prometheus.service
    daemon_reload: true
    state: restarted
    enabled: true
