apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-disconnected-dns-workaround
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,{{ lookup('template', './disconnected-dns-hosts') | b64encode }}
          verification: {}
        mode: 420
        overwrite: true
        path: /etc/hosts
