---
# disconnected-sync-acm-d default vars

# This will be your bastion machine (if you run setup-bastion playbook)
disconnected_registry_host: "{{ groups['bastion'][0] }}"
disconnected_registry_port: 5000

disconnected_sync_path: /opt/registry/sync-acm-d
