---
# install-wan-emulation tasks

- name: Install packages
  yum:
    name:
    - iproute-tc
    - net-tools
    - tcpdump
    state: present
    update_cache: true
    disable_gpg_check: yes

- name: Install kernel modules
  yum:
    name:
    - kernel-modules-extra
    - kernel-debug-modules-extra
    state: present
    update_cache: true
    disable_gpg_check: yes
  register: kernel_modules_installed

- name: Reboot if kernel modules installed
  when: kernel_modules_installed.changed
  block:
  - name: Reboot hypervisor
    shell: "sleep 5; reboot now"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for machine rebooting
    wait_for:
      port: 22
      delay: 2
      state: stopped
      host: "{{ inventory_hostname }}"
    delegate_to: localhost

  - name: Wait for machine to be ready after reboot
    wait_for_connection:
      delay: 120
      timeout: 1200
