---
# sync-operator-index tasks

- name: Create directories for syncing operator index
  file:
    path: "{{ item }}"
    state: directory
  loop:
   - "{{ sync_path }}"
   - "{{ sync_path }}/operators"
   - "{{ sync_path }}/operators/{{ operator_index_name }}"

- name: Create ImageSetConfiguration
  template:
    src: imagesetconf.yml.j2
    dest: "{{ sync_path }}/operators/{{ operator_index_name }}/imagesetconf.yml"

- name: Mirror operator index images
  shell: |
    oc mirror --authfile {{ registry_path }}/pull-secret-bastion.txt -c {{ sync_path }}/operators/{{ operator_index_name }}/imagesetconf.yml --workspace file://{{ sync_path }}/operators/{{ operator_index_name }} docker://{{ registry_host }}:{{ registry_port }} --v2

