---
# disconnected-sync-ocp-release tasks

- name: Mirror the repository
  shell: |
    oc adm release mirror \
      -a {{ registry_path }}/pull-secret-disconnected.txt \
      --from={{ ocp_release_image }} \
      --to-release-image={{ disconnected_registry_host }}:{{ disconnected_registry_port }}/{{ registry_repo }}:{{ ocp_release_image.split(":")[1] }} \
      --to={{ disconnected_registry_host }}:{{ disconnected_registry_port }}/{{ registry_repo }}
