- name: Stop and disable PCP services
  vars:
    pcp_services_list:
      - pmcd
      - pmlogger
  block:
    - name: Check if PCP services are running
      ansible.builtin.command: systemctl is-active {{ item }}
      ignore_errors: true
      register: pcp_services_active_status
      loop: "{{ pcp_services_list }}"

    - name: Stop PCP services
      when: item.stdout == 'active'
      ansible.builtin.systemd:
        name: "{{ item.item }}"
        state: stopped
      loop: "{{ pcp_services_active_status.results}}"

    - name: Check if PCP services exist
      ansible.builtin.command: systemctl is-enabled {{ item }}
      ignore_errors: true
      register: pcp_services_enabled_status
      loop: "{{ pcp_services_list }}"

    - name: Disable PCP services
      when: item.stdout == 'enabled'
      ansible.builtin.systemd:
        name: "{{ item.item }}"
        enabled: false
      loop: "{{ pcp_services_enabled_status.results}}"

- name: Unset selinux pcp boolean
  ansible.posix.seboolean:
    name: pcp_bind_all_unreserved_ports
    state: false
    persistent: true

- name: Remove PCP packages
  when: pcp_cleanup_remove_rpms | bool
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  loop:
    - pcp
    - pcp-system-tools

- name: Reconfigure firewall
  when: pcp_cleanup_remove_firewalld_rules | bool
  block:
    - name: Checkf if firewalld is running
      ansible.builtin.command: systemctl is-active firewalld
      ignore_errors: true
      register: pcp_cleanup_firewalld_running

    - name: Remove firewalld rules
      when: pcp_cleanup_firewalld_running.stdout == 'active'
      ansible.builtin.firewalld:
        port: 44321/tcp
        permanent: true
        immediate: true
        state: disabled

- name: Remove existing files
  when: pcp_cleanup_remove_remote_file | bool
  block:
    - name: Remove remote configuration file
      ansible.builtin.file:
        path: "{{ pcp_server_remote_file_path }}"
        state: absent

    - name: Remove old local log files
      ansible.builtin.file:
        path: "{{ pcp_log_dir }}/{{ ansible_hostname}}"
        state: absent

    - name: Remove old client log files
      when:
        - groups['hv'] is defined
        - groups['hv'] | length > 0
      ansible.builtin.file:
        path: "{{ pcp_log_dir }}/{{ item }}"
        state: absent
      loop:
        - "{{ groups['hv'] }}"
