---
# sno-create-ai-cluster default vars

# This will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: "{{ groups['bastion'][0] }}"
assisted_installer_port: 8090

# Manifest for KubeletConfig to adjust max pods
kubelet_config: false
