# Control flow variables
hv_metrics_sanity: false
hv_metrics_cleanup: false
hv_metrics_install_server: false
hv_metrics_install_client: false
hv_metrics_debug: false

# General configuration
hv_metrics_work_dir: "/root/hv-metrics"
hv_metrics_cleanup_keep_work_dir: false
hv_metrics_grafana_sidecar: true

# Pod configuration
hv_metrics_pod_type: "kube"
hv_metrics_pod_name: "hv-metrics"
hv_metrics_pod_port: "10999"

# Prometheus collector configuration
# Server configuration
hv_metrics_enable_local_prometheus: true
hv_metrics_server_address: localhost
hv_metrics_server_retention_time: "14d"

# Prometheus server container configuration
hv_metrics_server_podman_config_source: "{{ hv_metrics_work_dir }}/prometheus.yaml"
hv_metrics_server_podman_data_dir: "{{ hv_metrics_work_dir }}/data"

# Client configuration
hv_metrics_client_port: 9100
hv_metrics_scrape_interval: "15s"
hv_metrics_evaluation_interval: "15s"

# Grafana configuration
hv_metrics_grafana_username: "testadmin"
hv_metrics_grafana_password: "testadmin"
hv_metrics_grafana_dashboard_name: "hv-dashboard"

# Container configuration
hv_metrics_quadlet_dir: "/etc/containers/systemd"
hv_metrics_prometheus_container_image: "quay.io/prometheus/prometheus:latest"
hv_metrics_prometheus_container_name: "prometheus"
hv_metrics_node_exporter_container_image: "quay.io/prometheus/node-exporter:latest"
hv_metrics_node_exporter_container_name: "node-exporter"
hv_metrics_grafana_container_image: "docker.io/grafana/grafana:latest"
hv_metrics_grafana_container_name: "grafana"
