---
# boot-iso tasks

- name: Boot iso on dell hardware
  include_tasks: dell.yml
  with_items:
    - "{{ groups[inventory_group][:index|int] }}"
  when: hostvars[item]['vendor'] == 'Dell'

- name: Boot iso on hp hardware
  include_tasks: hp.yml
  with_items:
    - "{{ groups[inventory_group][:index|int] }}"
  when: hostvars[item]['vendor'] == 'Hp'

- name: Boot iso on Red Hat lab supermicro hardware
  include_tasks: supermicro.yml
  with_items:
    - "{{ groups[inventory_group][:index|int] }}"
  when:
  - hostvars[item]['vendor'] == 'Supermicro'
  - lab in rh_labs

- name: Boot iso on ibmcloud supermicro hardware
  include_tasks: ibmcloud-supermicro.yml
  with_items:
    - "{{ groups[inventory_group][:index|int] }}"
  when:
  - hostvars[item]['vendor'] == 'Supermicro'
  - lab in cloud_labs
