---
# Separate tasks to populate static network configuration

- name: RH Lab and BYOL Populate static network configuration
  set_fact:
    item_network_config:
      network_yaml: "{{ lookup('template', 'rhlab_nmstate.yml.j2') }}"
      mac_interface_map: "{{ lookup('template', 'rhlab_mac_interface_map.json.j2')  }}"
  when: lab in rh_labs or lab == "byol"

- name: Cloud Lab Populate static network configuration
  set_fact:
    item_network_config:
      network_yaml: "{{ lookup('template', 'ibmcloud_nmstate.yml.j2') }}"
      mac_interface_map: "{{ lookup('template', 'ibmcloud_mac_interface_map.json.j2')  }}"
  when: lab in cloud_labs

- name: Add {{ item }} ip config
  set_fact:
    static_network_config: "{{ static_network_config + [ item_network_config ] }}"
  when: item_network_config is defined
