---
# Separate tasks to populate static network configuration

- name: Assemble static network config for Red Hat labs
  set_fact:
    item_network_config:
      network_yaml: "{{ lookup('template', 'nmstate.yml.j2') }}"
      mac_interface_map: "{{ lookup('template', 'mac_interface_map.json.j2')  }}"
  when: lab in rh_labs

- name: Assemble static network config for ibmcloud lab
  set_fact:
    item_network_config:
      network_yaml: "{{ lookup('template', 'ibmcloud_nmstate.yml.j2') }}"
      mac_interface_map: "{{ lookup('template', 'ibmcloud_mac_interface_map.json.j2')  }}"
  when: lab in cloud_labs

- name: Add {{ item }} ip config
  set_fact:
    static_network_config: "{{ static_network_config + [ item_network_config ] }}"
