---
# Sample disconnected-sync-acm-d vars file

acm_snapshot: 2.6.0-DOWNSTREAM-2022-07-28-23-21-09

# Temporary fix to pull the correct image for this testing
# ztp_site_generator_image: quay.io/openshift-kni/ztp-site-generator
# ztp_site_generator_image: quay.io/melserng/ztp-site-generator
# ztp_site_generator_image_tag: 4.11.0
ztp_site_generator_image: registry-proxy.engineering.redhat.com/rh-osbs/openshift4-ztp-site-generate
ztp_site_generator_image_tag: v4.11.0

# TALO - Topology Aware Lifecycle Operator used with DU profile
cluster_group_upgrades_operator_image: quay.io/openshift-kni/cluster-group-upgrades-operator
cluster_group_upgrades_operator_image_tag: 4.11.0
cluster_group_upgrades_operator_precache_image: quay.io/openshift-kni/cluster-group-upgrades-operator-precache
cluster_group_upgrades_operator_precache_image_tag: 4.10.0
kube_rbac_proxy_image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0

minio_image: quay.io/minio/minio
minio_image_tag: RELEASE.2022-04-01T03-41-39Z

# Bundle only needs to be set if "download_mapping_file_from_deploy_repo" is false
acm_operator_bundle: v2.3.0-185

acm_d_pull_secret: "{{ lookup('file', '../pull_secret.acm_d.txt') }}"

download_mapping_file_from_deploy_repo: true
