---
# Hypervisor sample vars file

# Which lab to be deployed into (Ex scalelab)
lab:

ssh_public_key_file: ~/.ssh/id_rsa.pub

install_tc: true

# Enables using DHCP instead of relying on static network configuration for VMs
setup_hv_vm_dhcp: false

hv_vm_generate_manifests: true

# Types: sno, jumbo, multicluster
hv_vm_manifest_type: sno

# The cluster imageset used in the manifests
cluster_image_set: openshift-4.10.24

# Include ACM CRs in the manifests
hv_vm_manifest_acm_cr: false

# If hv_vm_manifest_type is set to multicluster, use these vars to adjust the count and size of clusters
# Careful not to exceed the count of your VMs, EX 4 * 60 means you must have 240 vms
multicluster_count: 4
multicluster_node_count: 60

# Retrieves the disconnected pull-secret instead of below pull-secret
use_disconnected_registry: false
# Provide pull-secret for non-disconnected manifests
pull_secret: "{{ lookup('file', '../pull_secret.txt') | b64encode }}"
