---
# Lab data (You should not have to edit this file)

# Bare-metal cloud environments
cloud_labs:
- ibmcloud

# Red Hat lab environments
rh_labs:
- performancelab
- scalelab
- byol

labs:
  performancelab:
    dns:
    - 10.6.60.1
    foreman: foreman.rdu3.labs.perfscale.redhat.com
    ntp_server: clock2.bos.redhat.com
    quads: quads.rdu3.labs.perfscale.redhat.com
  scalelab:
    dns:
    - 10.1.36.1
    - 10.1.36.2
    foreman: foreman.rdu2.scalelab.redhat.com
    ntp_server: clock1.rdu2.redhat.com
    quads: quads.rdu2.scalelab.redhat.com

# NOTE: This should map every server model in the Scale and Performance labs to
# the vendor. Right now, Jetlag supports only the Dell and Supermicro vendors,
# and others (e.g. NVIDIA dgx) will fail to map.
hw_vendor:
  mx750c: Dell
  r620: Dell
  r630: Dell
  r640: Dell
  r650: Dell
  r660: Dell
  r730xd: Dell
  r740xd: Dell
  r750: Dell
  r760: Dell
  r930: Dell
  fc640: Dell
  r6526: Dell
  r7425: Dell
  r7525: Dell
  r7625: Dell
  1029u: Supermicro
  1029p: Supermicro
  5039ms: Supermicro
  6018r: Supermicro
  6029p: Supermicro
  6029r: Supermicro
  6048r: Supermicro
  6048p: Supermicro
  6049p: Supermicro
  dl360: Hp

# This dictionary contains the expected nic names for networks in the scale lab. This determines the name of the
# nic for hypervisors. Expected OS is always RHEL 8.
# http://docs.scalelab.redhat.com/trac/scalelab/wiki/ScaleLabTipsAndTricks#RDU2ScaleLabPrivateNetworksandInterfaces
hw_nic_name:
  #$lab:
  #  $hw_name:
  #  - (nic 0 - public nic)
  #  - (nic 1 - Network 1)
  #  - (nic 2 - Network 2)
  #  ...
  # Thus hw_nic_name['scalelab']['r640'][1] = Network 1 = ens1f0
  scalelab:
    r630:
    - enp3s0f0
    - eno1
    - eno2
    - eno3
    - eno4
    r640:
    - eno1np0
    - ens1f0
    - ens1f1
    - ens2f0
    - ens2f1
    r650:
    - eno12399np0
    - ens1f0
    - ens1f1
    - ens2f0
    - ens2f1
    - eno12409np1
    r660:
    - eno12399np0
    - ens1f0
    - ens1f1
    - ens2f0
    - ens2f1
    - eno12409np1
    r730xd:
    - eno3
    - eno1
    - eno2
    - enp130s0f0
    - enp130s0f1
    r750:
    - eno8303
    - ens3f0
    - ens3f1
    - ens6f0
    - ens6f1
    r930:
    - em3
    - eno1
    - eno2
    - enp10s0f0
    - enp10s0f1
    fc640:
    - eno1
    - eno2
    - ens2f0
    - ens2f1
    6018r:
    - eno1
    - enp4s0f0
    - enp4s0f1
    - enp4s0f2
    - enp4s0f3
    6048r:
    - eno1
    - enp4s0f0
    - enp4s0f1
    - enp131s0f0
    - enp131s0f1
    1029u:
    - eno1
    - ens1f0
    - ens1f1
    - ens2f0
    - ens2f1
    1029p:
    - eno1
    - ens2f0
    - ens2f1
    - ens2f2
    - ens2f3
    5039ms:
    - enp2s0f0
    - enp1s0f0
    - enp1s0f1
    - enp2s0f1
    6049p:
    - eno1
    - ens3f0
    - ens3f1
    - ens2f0
    - ens2f1
    dl360:
    - eno5np0
    - ens2f0
    - ens2f1
    - ens1f0
    - ens1f1

# Based on VM Size (8vCPU, 18GiB Memory, 120G Disk)
hw_vm_counts:
  scalelab:
    r630:
      default: 2
      sdb: 2
    r640:
      default: 8
      sdb: 12
      nvme0n1: 12
    r650:
      default: 4
      nvme0n1: 23
    r660:
      default: 4
      nvme0n1: 23
    r730xd:
      default: 3
      nvme0n1: 3
    r750:
      default: 4
      nvme0n1: 23
    r930:
      default: 5
      nvme0n1: 14
    fc640:
      default: 8
    6018r:
      default: 2
    6048r:
      default: 8
    # Or potentially 13 on larger memory 1029u
    1029u:
      default: 0
      nvme0n1: 13
    1029p:
      default: 6
      nvme0n1: 7
    5039ms:
      default: 0
      sdb: 3
    6049p:
      default: 10
      nvme0n1: 10
    dl360:
      default: 8
      sdc: 12

# # Based on VM Size (8vCPU, 28GiB Memory, 120G Disk)
# hw_vm_counts:
#   scalelab:
#     r630:
#       default: 2
#       sdb: 2
#     r640:
#       default: 8
#       sdb: 5
#       nvme0n1: 5
#     r650:
#       default: 7
#       nvme0n1: 10
#     r730xd:
#       default: 2
#       nvme0n1: 2
#     r930:
#       default: 5
#       nvme0n1: 12
#     fc640:
#       default: 8
#     6018r:
#       default: 2
#     6048r:
#       default: 8
#     # Or potentially 13 on larger memory 1029u
#     1029u:
#       default: 0
#       nvme0n1: 8
#     1029p:
#       default: 4
#       nvme0n1: 4
#     5039ms:
#       default: 0
#       sdb: 2
#     6049p:
#       default: 5
#       nvme0n1: 8
#     dl360:
#       default: 5
#       sdc: 8
