---
# disconnected-sync-acm-d tasks

- name: Create directories for syncing acm
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ disconnected_sync_path }}"
  - "{{ disconnected_sync_path }}/acm"

- name: Template out pull-secret
  copy:
    content: "{{ acm_d_pull_secret }}"
    dest: "{{ disconnected_sync_path }}/pull-secret.acm_d.txt"

- name: Add disconnected registry to pull-secret
  shell: |
    b64auth=$( echo -n '{{ registry_user }}:{{ registry_password }}' | openssl base64 )
    AUTHSTRING="{\"{{ disconnected_registry_host }}:{{ disconnected_registry_port }}\": {\"auth\": \"$b64auth\",\"email\": \"openshift@redhat.com\" }}"
    jq -c ".auths += $AUTHSTRING" < {{ disconnected_sync_path }}/pull-secret.acm_d.txt > {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt

- name: Download acm mapping file from stolostron/deploy repo
  when: download_mapping_file_from_deploy_repo
  block:
  - name: Download the acm mapping file from github
    get_url:
      force: true
      url: "https://raw.githubusercontent.com/stolostron/deploy/master/mirror/{{ acm_snapshot }}.txt"
      dest: "{{ disconnected_sync_path }}/acm/mapping.txt"

  - name: Replacements in acm downloaded mapping file
    replace:
      path: "{{ disconnected_sync_path }}/acm/mapping.txt"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
      backup: true
    when: item.enabled | default(true) | bool
    loop:
    - regexp: "__DESTINATION_ORG__"
      replace: "{{ disconnected_registry_host }}:{{ disconnected_registry_port }}/acm-d"

- name: Generate acm mapping file from acm-custom-registry image
  when: not download_mapping_file_from_deploy_repo
  block:
  - name: Copy acm-custom-registry to disconnected registry
    shell: |
      skopeo copy --authfile {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt --all docker://quay.io:443/acm-d/acm-custom-registry:{{ acm_snapshot }} docker://{{ disconnected_registry_host }}:{{ disconnected_registry_port }}/acm-d/acm-custom-registry:{{ acm_snapshot }}

  - name: Copy acm-operator-bundle to disconnected registry
    shell: |
      skopeo copy --authfile {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt --all docker://quay.io:443/acm-d/acm-operator-bundle:{{ acm_operator_bundle }} docker://{{ disconnected_registry_host }}:{{ disconnected_registry_port }}/acm-d/acm-operator-bundle:{{ acm_operator_bundle }}

  - name: Generate acm container image mapping.txt
    shell: |
      oc adm catalog mirror -a {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt quay.io:443/acm-d/acm-custom-registry:{{ acm_snapshot }} {{ disconnected_registry_host }}:{{ disconnected_registry_port }} --manifests-only --to-manifests={{ disconnected_sync_path }}/acm/

  - name: Replacements in acm mapping file
    replace:
      path: "{{ disconnected_sync_path }}/acm/mapping.txt"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
      backup: true
    loop:
    - regexp: registry.redhat.io/rhacm2/
      replace: quay.io:443/acm-d/
    - regexp: "{{ disconnected_registry_host }}:{{ disconnected_registry_port }}/rhel8/postgresql-12"
      replace: "{{ disconnected_registry_host }}:{{ disconnected_registry_port }}/acm-d/postgresql-12"
    - regexp: rhacm2
      replace: acm-d

# If this errors, you won't be able to install ACM later, so retries are added incase of issues with the registry
- name: Mirror acm images onto the disconnected registry
  shell: |
    oc image mirror -a {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt -f {{ disconnected_sync_path }}/acm/mapping.txt --filter-by-os=.* --keep-manifest-list --continue-on-error=true --max-per-registry={{ max_per_registry }}
  register: result
  until: not result.failed
  retries: 3
  delay: 1

- name: Mirror ztp-site-generator image
  shell: |
    oc image mirror -a {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt {{ ztp_site_generator_image }} {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/openshift-kni/ztp-site-generator:latest --keep-manifest-list --continue-on-error=true

- name: Mirror cluster-group-upgrades-operator image
  shell: |
    oc image mirror -a {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt {{ cluster_group_upgrades_operator_image }}:{{ cluster_group_upgrades_operator_image_tag }} {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/openshift-kni/cluster-group-upgrades-operator:{{ cluster_group_upgrades_operator_image_tag }} --keep-manifest-list --continue-on-error=true

- name: Mirror kube-rbac-proxy image
  shell: |
    oc image mirror -a {{ disconnected_sync_path }}/pull-secret-disconnected.acm_d.txt {{ kube_rbac_proxy_image }} {{ disconnected_registry_host }}:{{ disconnected_registry_port }}/kubebuilder/kube-rbac-proxy:v0.8.0 --keep-manifest-list --continue-on-error=true
