---
# hv-vm-manifests-standard default vars

hv_vm_manifests_directory: /root/hv-vm

# 64 is a prefix for ipv6, 24 would work for ipv4
standard_cluster_network_host_prefix: 64

registry_path: /opt/registry

# Used with bmc-secret
bmc_username_base64: "{{ 'redhat' | b64encode }}"
bmc_password_base64: "{{ 'password' | b64encode }}"

# Used in conjunction with including the PerformanceProfile in the DU profile
siteconfig_enable_cpuset: false
siteconfig_cpuset: "0-3"

# Used in conjuntion with converged flow
siteconfig_baremetalhost_override_converged_flow: false

# Used with 4.12 SNOs when converged flow is enabled
siteconfig_ironic_inspect: false

# Used to enable observability in siteconfigs
siteconfig_observability: false
