---
# install-early-deps tasks
#
# Install what we need to run the playbooks
#

- name: Install python netaddr prereq
  yum:
    name:
    - python3-netaddr
    state: present
    update_cache: true
    disable_gpg_check: yes
  become: true

- name: Install ansible-galaxy collections
  command: ansible-galaxy collection install ansible.netcommon ansible.posix community.general containers.podman
  become: true
