---
# sno-post-cluster-install default vars

# This will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: "{{ groups['bastion'][0] }}"
assisted_installer_port: 8090

# Performance-addon-operator and du profile vars
install_performance_addon_operator: false
hugepages_count: 16
node: 0
isolated_cpus: 2-47,50-95

du_profile: false
operator_index_name: redhat-operator-index
operator_index_tag: v4.16
