---
# sno-install-cluster tasks

- name: Set networkType via install-config override
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v1/clusters/{{ item.value.cluster_id }}/install-config"
    method: PATCH
    body_format: json
    status_code: [201]
    return_content: true
    body: "\"{\\\"networking\\\": {\\\"networkType\\\": \\\"{{ networktype[cni_index|int] }}\\\" }}\""
  vars:
    cni_index: "{{ ai_indx % networktype|length }}"
  loop: "{{ ai_cluster_ids | dict2items  }}"
  loop_control:
    index_var: ai_indx

- name: Install cluster(s)
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v1/clusters/{{ item.value.cluster_id }}/actions/install"
    method: POST
    status_code: [202]
    return_content: true
    body_format: json
    body: { }
  loop: "{{ ai_cluster_ids | dict2items  }}"

- name: Set initial loop variables
  set_fact:
    boot_order_fixed_hosts: []

- name: Check if sno installed tasks loop
  include_tasks: check-sno-install.yml
