---
# sno-install-cluster tasks

- name: Get disconnected registry certificate
  slurp:
    src: "{{ registry_path }}/certs/domain.crt"
  register: mirror_cert
  when: use_disconnected_registry | default(false)

# The extra "| to_json(ensure_ascii=False) | string" adds an additional "layer"
# of escaping.  I am unsure of why I actually need this additional layer other
# than the api expects a string (and not actual json)
- name: Apply install-config overrides
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ item.value.cluster_id }}/install-config"
    method: PATCH
    body_format: json
    status_code: [201]
    return_content: true
    body: "{{ lookup('template', 'install-config-overrides.yml.j2') | from_yaml | to_json(ensure_ascii=False) | string | to_json(ensure_ascii=False) | string }}"
  register: get_install_config
  loop: "{{ ai_cluster_ids | dict2items  }}"

- name: Get host ids
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ item.value.cluster_id }}/hosts"
    method: GET
    body_format: json
    status_code: [200]
    return_content: true
  register: get_hosts
  with_items: "{{ ai_cluster_ids | dict2items  }}"
  when: sno_localstorage_configuration

- name: Apply sno host ignition config overrides
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/infra-envs/{{ item.infra_env_id }}/hosts/{{ item.id }}/ignition"
    method: PATCH
    body_format: json
    status_code: [201]
    return_content: true
    body: { "config": "{{ lookup('template', 'sno.ign.j2') | to_json }}" }
  with_items: "{{ get_hosts | json_query('results[*].json') }}"
  when: sno_localstorage_configuration

- name: Install cluster(s)
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ item.value.cluster_id }}/actions/install"
    method: POST
    status_code: [202]
    return_content: true
    body_format: json
    body: { }
  loop: "{{ ai_cluster_ids | dict2items  }}"

- name: Set initial loop variables
  set_fact:
    boot_order_fixed_hosts: []

- name: Check if sno installed tasks loop
  include_tasks: check-sno-install.yml
