---
# bastion-ocp-version default vars
release_urls:
  ga: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp"
  dev: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview"
  ci: "https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com"
payload_url: ""

# This will be your bastion machine (if you run setup-bastion playbook)
registry_host: "{{ groups['bastion'][0] }}"
registry_port: 5000

# This will be your bastion machine (if you run setup-bastion playbook)
http_store_host: "{{ groups['bastion'][0] }}"
http_store_port: 8081

ocp_version_path: /opt/ocp-version
