---
# hv-vm-manifests-multicluster tasks

- name: Create directories for hv-vm manifests on bastion for multicluster
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ hv_vm_manifests_directory }}/"
  - "{{ hv_vm_manifests_directory }}/multicluster"
  - "{{ hv_vm_manifests_directory }}/multicluster/manifests"

- name: Obtain pull-secret for disconnected
  slurp:
    src: "{{ registry_path }}/pull-secret-disconnected.txt"
  register: slurped_pull_secret
  when: use_disconnected_registry

- name: Set pull-secret for disconnected
  set_fact:
    pull_secret: "{{ slurped_pull_secret.content }}"
  when: use_disconnected_registry

- name: Template a manifest for multicluster
  template:
    src: manifest.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/multicluster/manifests/multicluster-{{ '%05x' | format(item) }}.yml"
  loop: "{{ range(1, multicluster_count + 1, 1) | list }}"
