---
# bastion-coredns tasks

- name: Stop and disable dnsmasq
  systemd:
    state: stopped
    enabled: false
    name: dnsmasq

- name: Create coredns directory
  file:
    path: /etc/coredns
    state: directory

- name: Configure Coredns / NetworkManager
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - src: "{{ 'Corefile.hosts.match.j2' if match_dns_to_inventory else 'Corefile.hosts.j2' }}"
      dest: /etc/coredns/Corefile.hosts
    - src: Corefile.j2
      dest: /etc/coredns/Corefile
    - src: 99-jetlag-dns.conf
      dest: /etc/NetworkManager/conf.d/99-jetlag-dns.conf
    - src: resolv.conf.j2
      dest: /etc/resolv.conf

- name: Restart NetworkManager
  systemd:
    state: restarted
    name: NetworkManager

- name: Start and enable coredns
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: coredns
