---
- block:
    - name: Increment the retry count
      set_fact:
        retry: "{{ 0 if retry is undefined else retry | int + 1 }}"

    - name: Pause during loop
      pause:
        seconds: "30"
      when: retry|int > 0

    - name: Get Pending CSRs
      shell: |
        KUBECONFIG={{ bastion_cluster_config_dir }}/kubeconfig oc get csr --no-headers | grep Pending | awk '{ print $1 }'
      register: oc_get_csr
    
    - name: Approve pending CSRs
      shell: |
              KUBECONFIG={{ bastion_cluster_config_dir }}/kubeconfig oc adm certificate approve {{ item }}
      loop: "{{ oc_get_csr.stdout_lines }}"
      when: oc_get_csr.stdout_lines | length > 0

    - name: Raise fail to trigger retry if CSRs still Pending
      fail:
        msg: CSRs still pending. Try again
      when: oc_get_csr.stdout_lines |length > 0
  rescue:
    - name: Fail on maximum retry count
      fail:
        msg: Maximum retries reached
      when: retry | int == 540

    - name: Retry the check
      include_tasks: check_nodes_joined.yml
