---
- name: Approve CSRs
  include_tasks: check_nodes_joined.yml

- name: Wait for expected number of workers to be Ready
  shell: |
    KUBECONFIG={{ bastion_cluster_config_dir }}/kubeconfig oc get nodes --no-headers -l node-role.kubernetes.io/worker | grep -c -v NotReady
  register: oc_get_nodes_workers
  until: oc_get_nodes_workers.stdout|int < current_worker_count+scale_out_count
  retries: 540
  delay: 30
