---
# bastion-dnsmasq tasks

- name: Configure Dnsmasq / NetworkManager
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: jetlag.conf.j2
    dest: /etc/dnsmasq.d/jetlag.conf
  - src: 99-jetlag-dns.conf
    dest: /etc/NetworkManager/conf.d/99-jetlag-dns.conf
  - src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Restart NetworkManager
  systemd:
    state: restarted
    name: NetworkManager

- name: Start and enable dnsmasq
  systemd:
    state: restarted
    enabled: true
    name: dnsmasq
