---
# hv-install tasks

- name: Install packages
  dnf:
    name:
    - "@virt"
    - virt-install
    - virt-viewer
    - gcc
    - python3-devel
    - libvirt-devel
    state: present
    update_cache: true
    disable_gpg_check: yes

- name: Install python packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  loop:
  - name: libvirt-python
    version: 6.0.0
  - name: sushy-tools
    version: 0.16.0

- name: Get coredns
  get_url:
    validate_certs: false
    force: true
    url: https://github.com/coredns/coredns/releases/download/v1.10.1/coredns_1.10.1_linux_amd64.tgz
    dest: /root/coredns_1.10.1_linux_amd64.tgz

- name: Untar coredns
  unarchive:
    src: /root/coredns_1.10.1_linux_amd64.tgz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0700

- name: Setup chronyd
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: true
    mode: "0644"

- name: Ensure chronyd is running with new configuration
  systemd:
    state: restarted
    enabled: true
    name: chronyd

- name: Copying the public key to the root user's authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ ssh_public_key_file }}') }}"

- name: Start and enable KSM
  systemd:
    state: started
    enabled: true
    name: ksm

- name: Start and enable KSMtuned
  systemd:
    state: started
    enabled: true
    name: ksmtuned
