---
# hv-install tasks

- name: Install packages
  dnf:
    name:
    - "@virt"
    - virt-install
    - virt-viewer
    - gcc
    - python3-devel
    state: present
    update_cache: true
    disable_gpg_check: yes

- name: Install python packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  loop:
  - name: libvirt-python
    version: 4.5.0
  - name: sushy-tools
    version: 0.16.0
