---
# hv-install tasks

- name: Install packages
  dnf:
    name:
    - "@virt"
    - virt-install
    - virt-viewer
    - gcc
    - python3-devel
    - libvirt-devel
    state: present
    update_cache: true
    disable_gpg_check: yes

- name: Install python packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  loop:
  - name: libvirt-python
    version: 6.0.0
  - name: sushy-tools
    version: 0.16.0

- name: Setup chronyd
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: true

- name: Ensure chronyd is running with new configuration
  systemd:
    state: restarted
    enabled: true
    name: chronyd

- name: Copying the public key to the root user's authorized_keys
  copy:
    src: "{{ ssh_public_key_file }}"
    dest: /root/.ssh/authorized_keys
    mode: 0600
