---
# hv-sno-create-manifests default vars

hv_sno_manifests_directory: /root/hv-sno

cluster_image_set: openshift-4.10.6

registry_path: /opt/registry

# Used with bmc-secret
bmc_username_base64: "{{ 'redhat' | b64encode }}"
bmc_password_base64: "{{ 'password' | b64encode }}"

# Used in conjunction with including the PerformanceProfile in the DU profile
siteconfig_enable_cpuset: false
siteconfig_cpuset: "0-3"
