---
# Render Coredns.hosts template to match provided ansible inventory
# Requires to run with vm-planner.py generated inventory
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/bastion-match-coredns-to-inventory.yml
#

- name: Render Coredns.hosts template to match provided ansible inventory
  hosts: bastion
  gather_facts: false
  vars_files:
    - vars/lab.yml
    - vars/all.yml
  roles:
    - role: bastion-coredns
      vars:
        match_dns_to_inventory: true
