---
# exists for backwards compatibility
# you should be using mno-deploy
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/mno-deploy.yml
#

- name: Backwards compatible pause
  hosts: localhost
  tasks:
    - ansible.builtin.pause:
        prompt: "bm-deploy.yml is now called mno-deploy.yml. Please update your invocation to use the new name."
        minutes: 1

- name: bm-deploy is now called mno-deploy, calling mno-deploy for you.
  ansible.builtin.import_playbook: mno-deploy.yml
