---
# Sync an OCP release to the disconnected registry. This simplifies adding a new
# release that could be different from the original release that was synced to
# the disconnected registry during the initial bastion setup.
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud03.local ansible/disconnected-sync-ocp-release.yml
#

- name: Sync OCP release container images into disconnected registry
  hosts: bastion
  gather_facts: false
  vars_files:
  - vars/disconnected-sync-ocp-release.yml
  roles:
  - role: bastion-ocp-version
    vars:
      setup_bastion: false
  - disconnected-sync-ocp-release
