---
# Sync an specific operator index to the disconnected registry.
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud03.local ansible/disconnected-sync-operator-index.yml
#

- name: Sync operator index and container images into disconnected registry
  hosts: bastion
  gather_facts: false
  vars_files:
  - vars/all.yml
  - vars/disconnected-sync-operator-index.yml
  roles:
  - disconnected-sync-operator-index
