---
# Replaces VMs on hypervisors
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/hv-vm-replace.yml
#

- name: Delete VMs on hypervisors
  hosts: hv_vm
  gather_facts: false
  vars_files:
  - vars/hv.yml
  roles:
  - hv-vm-delete

- name: Cleanup hypervisors after clearing off VMs
  hosts: hv
  gather_facts: false
  tasks:
  - name: Restart sushy-emulator
    systemd:
      state: restarted
      enabled: true
      name: sushy-emulator

  - name: Clean up directory where boot iso files can accumulate
    file:
      path: /var/lib/libvirt/images/
      state: absent

  - name: Ensure libvirt images directory exists
    file:
      path: /var/lib/libvirt/images/
      state: directory

- name: Create VMs on hypervisors
  hosts: hv_vm
  gather_facts: false
  vars_files:
  - vars/hv.yml
  roles:
  - hv-vm-create
  - role: hv-vm-manifests-sno
    when:
    - hv_vm_generate_manifests
    - hv_vm_manifest_type == "sno"

- name: Create compact/standard/jumbo cluster manifests
  hosts: bastion
  gather_facts: false
  vars_files:
  - vars/hv.yml
  roles:
  - role: hv-vm-manifests-compact
    when:
    - hv_vm_generate_manifests
    - hv_vm_manifest_type == "compact"
  - role: hv-vm-manifests-standard
    when:
    - hv_vm_generate_manifests
    - hv_vm_manifest_type == "standard"
  - role: hv-vm-manifests-jumbo
    when:
    - hv_vm_generate_manifests
    - hv_vm_manifest_type == "jumbo"
