---
# Create and deploy a cluster with the Assisted Installer on IBMcloud
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/ibmcloud.local ansible/ibmcloud-bm-deploy.yml
#

- name: Creates a bare metal cluster with the assisted-installer on ibmcloud
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/ibmcloud.yml
  vars:
    assisted_installer_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
    http_store_host: "{{ hostvars[inventory_hostname]['private_address'] }}"
  roles:
  - validate-vars
  - ocp-release
  - ibmcloud-create-ai-cluster
  - generate-discovery-iso
  - role: boot-iso
    vars:
      inventory_group: controlplane
      index: 3
  - role: boot-iso
    vars:
      inventory_group: worker
      index: "{{ worker_node_count }}"
  - wait-hosts-discovered
  - configure-local-storage
  - install-cluster
  - bm-post-cluster-install
