---
# Create and deploy a cluster with the Assisted Installer
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/mno-deploy.yml
#

- name: Creates a multi node cluster with the assisted-installer
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/all.yml
  pre_tasks:
  - name: Validate deploying MNO
    fail:
      msg: "cluster_type is not 'mno' or 'vmno'"
    when: cluster_type != "mno" and cluster_type != "vmno"
  roles:
  - validate-vars
  - ocp-release
  - create-ai-cluster
  - generate-discovery-iso
  - role: boot-iso
    vars:
      inventory_group: controlplane
      index: 3
  - role: boot-iso
    vars:
      inventory_group: worker
      index: "{{ worker_node_count|int + (hybrid_worker_count | default(0)) }}"
  - wait-hosts-discovered
  - configure-local-storage
  - install-cluster

  tasks:
  - name: Check if sync-operator-index file exists
    ansible.builtin.stat:
      path: "vars/sync-operator-index.yml"
    register: var_file_status

  - name: Load var file needed by mno-post-cluster-install (override defaults)
    ansible.builtin.include_vars:
      file: "vars/sync-operator-index.yml"
    when: var_file_status.stat.exists

  - name: Execute mno-post-cluster-install role
    ansible.builtin.import_role:
      name: mno-post-cluster-install
