---
# Setup bastion machine to deploy an OCP cluster
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/setup-bastion.yml
#

- name: Setup bastion machine
  hosts: bastion
  vars_files:
  - vars/lab.yml
  - vars/all.yml

  tasks:
  - name: Execute validate-vars role
    ansible.builtin.include_role:
      name: validate-vars

  - name: Execute ocp-release role
    ansible.builtin.include_role:
      name: ocp-release

  - name: Execute bastion-install role
    ansible.builtin.include_role:
      name: bastion-install

  - name: Execute bastion-network role
    ansible.builtin.include_role:
      name: bastion-network

  - name: Execute bastion-dnsmasq role
    ansible.builtin.include_role:
      name: bastion-dnsmasq
    when: not setup_coredns

  - name: Execute bastion-coredns role
    ansible.builtin.include_role:
      name: bastion-coredns
    when: setup_coredns

  - name: Execute bastion-http role
    ansible.builtin.include_role:
      name: bastion-http

  - name: Execute bastion-ocp-version role
    ansible.builtin.include_role:
      name: bastion-ocp-version

  - name: Execute bastion-registry role
    ansible.builtin.include_role:
      name: bastion-registry
    when: setup_bastion_registry

  - name: Handle Sync Operator Index configurations and execution
    when:
    - setup_bastion_registry
    - sync_operator_index | default(false)
    block:
    - name: Load specific sync-operator-index variables
      ansible.builtin.include_vars:
        file: vars/sync-operator-index.yml

    - name: Execute sync-operator-index role
      ansible.builtin.include_role:
        name: sync-operator-index

  - name: Execute sync-ocp-release role
    ansible.builtin.include_role:
      name: sync-ocp-release
    when:
    - setup_bastion_registry
    - sync_ocp_release | default(false)

  - name: Execute bastion-proxy role
    ansible.builtin.include_role:
      name: bastion-proxy
    when: setup_bastion_proxy | default(false)

  - name: Execute bastion-assisted-installer role
    ansible.builtin.include_role:
      name: bastion-assisted-installer

  - name: Execute bastion-gogs role
    ansible.builtin.include_role:
      name: bastion-gogs
    when: setup_bastion_gogs

  - name: Execute bastion-disconnected-haproxy role
    ansible.builtin.include_role:
      name: bastion-disconnected-haproxy
    when: use_bastion_registry or setup_bastion_proxy | default(false)

  - name: Execute hv-metrics-server role
    ansible.builtin.include_role:
      name: hv-metrics-server
    when: setup_hv_metrics | default(false) | bool

  - name: Execute bastion-minio role
    ansible.builtin.include_role:
      name: bastion-minio
    when: setup_bastion_minio | default(false)
