---
# Disables igb VFs from attempting to connect, which never succeeds and thus drives up CPU across all the workers.
#
# Exepects an inventory that has only the [worker] block, as with the normal inventory created where workers show up under [worker] and [hv_vm] seem to have some variables that affect how the node is accessed.
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/vm-sriov-disable.yml
#

- name: Disable all fake sr-iov devices and connections
  gather_facts: false
  hosts: worker
  tasks:
    - name: devices down
      shell:
        for i in {5..10} ; do for j in {0..6} ; do nmcli d down enp${i}s0v${j}  ; done ; done
      become: true
      ignore_errors: true

    - name: connections autoconnect off
      shell:
        for i in $( nmcli conn show | grep "Wired connection" | awk '{ print $4 }' ) ; do nmcli conn mod $i connection.autoconnect no ; done
      become: true
      ignore_errors: true
