---
# hv-vm-manifests-standard tasks

- name: Create directories for hv-vm manifests on bastion for standard clusters
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ hv_vm_manifests_directory }}/"
  - "{{ hv_vm_manifests_directory }}/standard"
  - "{{ hv_vm_manifests_directory }}/standard/manifests"
  - "{{ hv_vm_manifests_directory }}/standard/siteconfigs"

- name: Obtain pull-secret for bastion registry
  slurp:
    src: "{{ registry_path }}/pull-secret-bastion.txt"
  register: slurped_pull_secret
  when: use_bastion_registry

- name: Set pull-secret for bastion registry
  set_fact:
    pull_secret: "{{ slurped_pull_secret.content }}"
  when: use_bastion_registry

- name: Fast create directory for each cluster
  shell: |
    {% for item in (range(1, standard_cluster_count + 1, 1) | list) %}
    mkdir -p {{ hv_vm_manifests_directory }}/standard/manifests/standard-{{ '%05d' | format(item) }}
    {% endfor %}

- name: Template complete manifests per cluster
  template:
    src: manifest.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/standard/manifests/standard-{{ '%05d' | format(item) }}/manifest.yml"
  loop: "{{ range(1, standard_cluster_count + 1, 1) | list }}"

- name: Template acm managedcluster manifests per cluster
  template:
    src: managedcluster.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/standard/manifests/standard-{{ '%05d' | format(item) }}/managedcluster.yml"
  loop: "{{ range(1, standard_cluster_count + 1, 1) | list }}"

- name: Template a siteconfig per cluster
  template:
    src: siteconfig.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/standard/siteconfigs/standard-{{ '%05d' | format(item) }}-siteconfig.yml"
  loop: "{{ range(1, standard_cluster_count + 1, 1) | list }}"

- name: Template a siteconfig-resources per cluster
  template:
    src: siteconfig-resources.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/standard/siteconfigs/standard-{{ '%05d' | format(item) }}-resources.yml"
  loop: "{{ range(1, standard_cluster_count + 1, 1) | list }}"
