---
# cluster_name applies only to bm/rwn clusters, sno clusters use base host name as the cluster name
cluster_name: bm
base_dns_name: example.com

# bastion dnsmasq clusterdeployment entries (Enables hub cluster to provision spoke clusters via clusterdeployments)
# the default count of 0 ignores setting this up
bastion_dnsmasq_cd_prefix: sno
bastion_dnsmasq_cd_network: "{{ controlplane_network }}"
bastion_dnsmasq_cd_network_offset: 14
bastion_dnsmasq_cd_network_count: 0

# Appends each entry to /etc/hosts of bastion machine during cluster install to
# allow sshuttle easy resolution when proxying into cluster
etc_hosts_ingress_routes:
- oauth-openshift
- console-openshift-console
- downloads-openshift-console
- cluster-openshift-gitops
- kam-openshift-gitops
- openshift-gitops-server-openshift-gitops
- canary-openshift-ingress-canary
- alertmanager-main-openshift-monitoring
- grafana-openshift-monitoring
- prometheus-k8s-openshift-monitoring
- thanos-querier-openshift-monitoring
- assisted-image-service-open-cluster-management
- assisted-service-open-cluster-management
- multicloud-console
- dittybopper-dittybopper
