---
# cluster_name applies only to bm/rwn clusters, sno clusters use base host name as the cluster name
cluster_name: bm
base_dns_name: example.com

# Appends each entry to /etc/hosts of bastion machine during cluster install to
# allow sshuttle easy resolution when proxying into cluster
etc_hosts_ingress_routes:
- assisted-image-service-multicluster-engine
- assisted-service-multicluster-engine
- multicloud-console
- oauth-openshift
- console-openshift-console
- downloads-openshift-console
- cluster-openshift-gitops
- kam-openshift-gitops
- openshift-gitops-server-openshift-gitops
- canary-openshift-ingress-canary
- alertmanager-main-openshift-monitoring
- grafana-openshift-monitoring
- prometheus-k8s-openshift-monitoring
- thanos-querier-openshift-monitoring
- assisted-image-service-open-cluster-management
- assisted-service-open-cluster-management
- dittybopper-dittybopper
- minio-minio

# Default number of additional dns entries to add in the event we have hypervisor machines with VMs.
# Ignore if you are not doing anything with hypervisor machines and VMs
multicluster_count: 4
